// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestProto.proto

package eecs441.shareeditor.proto;

public final class TestProto {
  private TestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface EventOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 id = 1;
    /**
     * <code>required int32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int32 id = 1;</code>
     */
    int getId();

    // optional int32 cursorpos = 2;
    /**
     * <code>optional int32 cursorpos = 2;</code>
     */
    boolean hasCursorpos();
    /**
     * <code>optional int32 cursorpos = 2;</code>
     */
    int getCursorpos();

    // optional string beforetext = 3;
    /**
     * <code>optional string beforetext = 3;</code>
     */
    boolean hasBeforetext();
    /**
     * <code>optional string beforetext = 3;</code>
     */
    java.lang.String getBeforetext();
    /**
     * <code>optional string beforetext = 3;</code>
     */
    com.google.protobuf.ByteString
        getBeforetextBytes();

    // optional string aftertext = 4;
    /**
     * <code>optional string aftertext = 4;</code>
     */
    boolean hasAftertext();
    /**
     * <code>optional string aftertext = 4;</code>
     */
    java.lang.String getAftertext();
    /**
     * <code>optional string aftertext = 4;</code>
     */
    com.google.protobuf.ByteString
        getAftertextBytes();
  }
  /**
   * Protobuf type {@code eecs441.shareeditor.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessage
      implements EventOrBuilder {
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Event defaultInstance;
    public static Event getDefaultInstance() {
      return defaultInstance;
    }

    public Event getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cursorpos_ = input.readInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              beforetext_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              aftertext_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eecs441.shareeditor.proto.TestProto.internal_static_eecs441_shareeditor_Event_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eecs441.shareeditor.proto.TestProto.internal_static_eecs441_shareeditor_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eecs441.shareeditor.proto.TestProto.Event.class, eecs441.shareeditor.proto.TestProto.Event.Builder.class);
    }

    public static com.google.protobuf.Parser<Event> PARSER =
        new com.google.protobuf.AbstractParser<Event>() {
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>required int32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    // optional int32 cursorpos = 2;
    public static final int CURSORPOS_FIELD_NUMBER = 2;
    private int cursorpos_;
    /**
     * <code>optional int32 cursorpos = 2;</code>
     */
    public boolean hasCursorpos() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 cursorpos = 2;</code>
     */
    public int getCursorpos() {
      return cursorpos_;
    }

    // optional string beforetext = 3;
    public static final int BEFORETEXT_FIELD_NUMBER = 3;
    private java.lang.Object beforetext_;
    /**
     * <code>optional string beforetext = 3;</code>
     */
    public boolean hasBeforetext() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string beforetext = 3;</code>
     */
    public java.lang.String getBeforetext() {
      java.lang.Object ref = beforetext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          beforetext_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string beforetext = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBeforetextBytes() {
      java.lang.Object ref = beforetext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        beforetext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string aftertext = 4;
    public static final int AFTERTEXT_FIELD_NUMBER = 4;
    private java.lang.Object aftertext_;
    /**
     * <code>optional string aftertext = 4;</code>
     */
    public boolean hasAftertext() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string aftertext = 4;</code>
     */
    public java.lang.String getAftertext() {
      java.lang.Object ref = aftertext_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          aftertext_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string aftertext = 4;</code>
     */
    public com.google.protobuf.ByteString
        getAftertextBytes() {
      java.lang.Object ref = aftertext_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        aftertext_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      id_ = 0;
      cursorpos_ = 0;
      beforetext_ = "";
      aftertext_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cursorpos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBeforetextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getAftertextBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cursorpos_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBeforetextBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getAftertextBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eecs441.shareeditor.proto.TestProto.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eecs441.shareeditor.proto.TestProto.Event prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eecs441.shareeditor.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements eecs441.shareeditor.proto.TestProto.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eecs441.shareeditor.proto.TestProto.internal_static_eecs441_shareeditor_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eecs441.shareeditor.proto.TestProto.internal_static_eecs441_shareeditor_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eecs441.shareeditor.proto.TestProto.Event.class, eecs441.shareeditor.proto.TestProto.Event.Builder.class);
      }

      // Construct using eecs441.shareeditor.proto.TestProto.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cursorpos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        beforetext_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        aftertext_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eecs441.shareeditor.proto.TestProto.internal_static_eecs441_shareeditor_Event_descriptor;
      }

      public eecs441.shareeditor.proto.TestProto.Event getDefaultInstanceForType() {
        return eecs441.shareeditor.proto.TestProto.Event.getDefaultInstance();
      }

      public eecs441.shareeditor.proto.TestProto.Event build() {
        eecs441.shareeditor.proto.TestProto.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eecs441.shareeditor.proto.TestProto.Event buildPartial() {
        eecs441.shareeditor.proto.TestProto.Event result = new eecs441.shareeditor.proto.TestProto.Event(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cursorpos_ = cursorpos_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.beforetext_ = beforetext_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.aftertext_ = aftertext_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eecs441.shareeditor.proto.TestProto.Event) {
          return mergeFrom((eecs441.shareeditor.proto.TestProto.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eecs441.shareeditor.proto.TestProto.Event other) {
        if (other == eecs441.shareeditor.proto.TestProto.Event.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasCursorpos()) {
          setCursorpos(other.getCursorpos());
        }
        if (other.hasBeforetext()) {
          bitField0_ |= 0x00000004;
          beforetext_ = other.beforetext_;
          onChanged();
        }
        if (other.hasAftertext()) {
          bitField0_ |= 0x00000008;
          aftertext_ = other.aftertext_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eecs441.shareeditor.proto.TestProto.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eecs441.shareeditor.proto.TestProto.Event) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 id = 1;
      private int id_ ;
      /**
       * <code>required int32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cursorpos = 2;
      private int cursorpos_ ;
      /**
       * <code>optional int32 cursorpos = 2;</code>
       */
      public boolean hasCursorpos() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cursorpos = 2;</code>
       */
      public int getCursorpos() {
        return cursorpos_;
      }
      /**
       * <code>optional int32 cursorpos = 2;</code>
       */
      public Builder setCursorpos(int value) {
        bitField0_ |= 0x00000002;
        cursorpos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cursorpos = 2;</code>
       */
      public Builder clearCursorpos() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cursorpos_ = 0;
        onChanged();
        return this;
      }

      // optional string beforetext = 3;
      private java.lang.Object beforetext_ = "";
      /**
       * <code>optional string beforetext = 3;</code>
       */
      public boolean hasBeforetext() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string beforetext = 3;</code>
       */
      public java.lang.String getBeforetext() {
        java.lang.Object ref = beforetext_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          beforetext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string beforetext = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBeforetextBytes() {
        java.lang.Object ref = beforetext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          beforetext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string beforetext = 3;</code>
       */
      public Builder setBeforetext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        beforetext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string beforetext = 3;</code>
       */
      public Builder clearBeforetext() {
        bitField0_ = (bitField0_ & ~0x00000004);
        beforetext_ = getDefaultInstance().getBeforetext();
        onChanged();
        return this;
      }
      /**
       * <code>optional string beforetext = 3;</code>
       */
      public Builder setBeforetextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        beforetext_ = value;
        onChanged();
        return this;
      }

      // optional string aftertext = 4;
      private java.lang.Object aftertext_ = "";
      /**
       * <code>optional string aftertext = 4;</code>
       */
      public boolean hasAftertext() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string aftertext = 4;</code>
       */
      public java.lang.String getAftertext() {
        java.lang.Object ref = aftertext_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          aftertext_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string aftertext = 4;</code>
       */
      public com.google.protobuf.ByteString
          getAftertextBytes() {
        java.lang.Object ref = aftertext_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          aftertext_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string aftertext = 4;</code>
       */
      public Builder setAftertext(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        aftertext_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string aftertext = 4;</code>
       */
      public Builder clearAftertext() {
        bitField0_ = (bitField0_ & ~0x00000008);
        aftertext_ = getDefaultInstance().getAftertext();
        onChanged();
        return this;
      }
      /**
       * <code>optional string aftertext = 4;</code>
       */
      public Builder setAftertextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        aftertext_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eecs441.shareeditor.Event)
    }

    static {
      defaultInstance = new Event(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eecs441.shareeditor.Event)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_eecs441_shareeditor_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eecs441_shareeditor_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017TestProto.proto\022\023eecs441.shareeditor\"M" +
      "\n\005Event\022\n\n\002id\030\001 \002(\005\022\021\n\tcursorpos\030\002 \001(\005\022\022" +
      "\n\nbeforetext\030\003 \001(\t\022\021\n\taftertext\030\004 \001(\tB\033\n" +
      "\031eecs441.shareeditor.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_eecs441_shareeditor_Event_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_eecs441_shareeditor_Event_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_eecs441_shareeditor_Event_descriptor,
              new java.lang.String[] { "Id", "Cursorpos", "Beforetext", "Aftertext", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
